[package]
name = "egomoose/gravity-camera"
version = "573.0.5730507"
description = "https://github.com/EgoMoose/gravity-camera"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayerModule = "upliftgames/playermodule@573.0.5730507"