[package]
name = "egomoose/gravity-camera"
version = "608.1.6080485"
description = "https://github.com/EgoMoose/gravity-camera"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayerModule = "upliftgames/playermodule@608.1.6080485"