[package]
name = "egomoose/gravity-camera"
version = "654.1.6540477"
description = "https://github.com/EgoMoose/gravity-camera"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayerModule = "upliftgames/playermodule@654.1.6540477"