[package]
name = "egomoose/gravity-camera"
version = "569.2.5690484"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayerModule = "upliftgames/playermodule@569.2.5690484"